# Tester la route pour obtenir tous les Pokémons
GET http://localhost:3000/api/pokemons
Accept: application/json

###

# Tester la route pour obtenir un Pokémon par ID
GET http://localhost:3000/api/pokemons/7
Accept: application/json

###

# Tester la route pour obtenir tous les Types
GET http://localhost:3000/api/types
Accept: application/json

###

# Tester la route pour obtenir les Pokémons par Type
GET http://localhost:3000/api/types/1/pokemons
Accept: application/json

###

# Tester la route pour obtenir toutes les Équipes
GET http://localhost:3000/api/teams
Accept: application/json

###

# Tester la route pour obtenir une Équipe par ID
GET http://localhost:3000/api/teams/1
Accept: application/json

### Création d'une nouvelle équipe
POST http://localhost:3000/api/teams
Content-Type: application/json

{
  "name": "Team Test",
  "description": "This is a test team.",
  "pokemons": [1, 2, 3, 4, 5]
}

### Enregistrer un vote pour le Pokémon avec l'ID 1
POST http://localhost:3000/api/pokemons/1/vote
Content-Type: application/json

{
  "votes": 1
}

### Enregistrer un vote pour le Pokémon avec l'ID 2
POST http://localhost:3000/api/pokemons/2/vote
Content-Type: application/json

{
  "votes": 5
}

### Récupérer le classement des Pokémon les plus votés
GET http://localhost:3000/api/pokemons/ranking

